2025-06-24 16:01:07,502 INFO    MainThread:8021 [wandb_setup.py:_flush():81] Current SDK version is 0.20.1
2025-06-24 16:01:07,502 INFO    MainThread:8021 [wandb_setup.py:_flush():81] Configure stats pid to 8021
2025-06-24 16:01:07,502 INFO    MainThread:8021 [wandb_setup.py:_flush():81] Loading settings from /tmlscratch/narashim/.config/wandb/settings
2025-06-24 16:01:07,502 INFO    MainThread:8021 [wandb_setup.py:_flush():81] Loading settings from /tmlscratch/narashim/In_Context_Learning/wandb/settings
2025-06-24 16:01:07,503 INFO    MainThread:8021 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-06-24 16:01:07,504 INFO    MainThread:8021 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /tmlscratch/narashim/In_Context_Learning/wandb/run-20250624_160107-4phhj1yv/logs/debug.log
2025-06-24 16:01:07,504 INFO    MainThread:8021 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /tmlscratch/narashim/In_Context_Learning/wandb/run-20250624_160107-4phhj1yv/logs/debug-internal.log
2025-06-24 16:01:07,505 INFO    MainThread:8021 [wandb_init.py:init():831] calling init triggers
2025-06-24 16:01:07,506 INFO    MainThread:8021 [wandb_init.py:init():836] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'epochs': 1000000, 'batch_size': 64, 'order': 1, 'vocab_size': 5, 'sequence_length': 128, 'device': 'cuda', 'initialize': {'qk': ['uniform', 0.1], 'v': ['uniform', 0.1], 'output_proj': ['constant', 0.01]}, '_wandb': {}}
2025-06-24 16:01:07,506 INFO    MainThread:8021 [wandb_init.py:init():872] starting backend
2025-06-24 16:01:07,731 INFO    MainThread:8021 [wandb_init.py:init():875] sending inform_init request
2025-06-24 16:01:07,738 INFO    MainThread:8021 [wandb_init.py:init():883] backend started and connected
2025-06-24 16:01:07,739 INFO    MainThread:8021 [wandb_init.py:init():956] updated telemetry
2025-06-24 16:01:07,755 INFO    MainThread:8021 [wandb_init.py:init():980] communicating run to backend with 90.0 second timeout
2025-06-24 16:01:08,294 INFO    MainThread:8021 [wandb_init.py:init():1032] starting run threads in backend
2025-06-24 16:01:08,403 INFO    MainThread:8021 [wandb_run.py:_console_start():2453] atexit reg
2025-06-24 16:01:08,403 INFO    MainThread:8021 [wandb_run.py:_redirect():2301] redirect: wrap_raw
2025-06-24 16:01:08,404 INFO    MainThread:8021 [wandb_run.py:_redirect():2370] Wrapping output streams.
2025-06-24 16:01:08,404 INFO    MainThread:8021 [wandb_run.py:_redirect():2393] Redirects installed.
2025-06-24 16:01:08,409 INFO    MainThread:8021 [wandb_init.py:init():1078] run started, returning control to user process
2025-06-24 16:02:11,412 INFO    MsgRouterThr:8021 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 2 handles.
2025-06-24 16:02:52,712 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,737 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,738 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,739 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,740 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,743 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,744 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,744 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,744 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,746 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,747 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,747 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,748 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,752 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,752 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,753 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,754 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,758 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,758 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,759 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,760 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,762 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,762 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,763 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,764 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,765 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,765 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,766 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,767 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,768 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,769 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-24 16:02:52,770 ERROR   MainThread:8021 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/tmlscratch/narashim/miniconda3/envs/myenv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
